description: Derivation activity
$defs:
  Derivation:
    allOf:
      - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Activity
      - properties:
          provType:
            type: array
            contains:
              type: string
              const: Derivation
        required:
          - provType
          - generated
          - used

anyOf:
  - $ref: "#/$defs/Derivation"
