prefix prov: <http://www.w3.org/ns/prov#>
SELECT $agent ?p ?plabel ?o ?olabel
WHERE {
    $agent  ?p ?o .
    OPTIONAL { ?p rdfs:label ?plabel }
    OPTIONAL { ?o rdfs:label ?olabel }
    OPTIONAL {
    FILTER(isBlank(?o))
    ?o rdfs:label ?blankNodeLabel .
  }
       
}