description: Aggregation activity
$defs:
  Aggregation:
    allOf:
      - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Activity
      - properties:
          provType:
            type: array
            contains:
              type: string
              const: Aggregation
        required:
          - provType
          - generated
          - used

anyOf:
  - $ref: "#/$defs/Aggregation"
